function buildGatewayResponse({
  checkId,
  gatewayPatientId,
  submissionType,
  patientFirstName,
  patientLastName,
  patientDob,
  payerId,
  payerName,
  memberId,
  providerNpi,
  serviceDate,
  serviceTypeCode = "30",
  coverageStatus,
  planName,
  planType,
  networkStatus,
  effectiveDate,
  terminationDate,
  groupNumber,
  confidenceScore,
  responseTimeSeconds,
  priorAuthRequired,
  requiresHumanReview,
  flags,
}) {
  return {
    routing_header: {
      module: "EV",
      submission_type: submissionType,
      emr_type: "",
    },
    request: {
      patient_id: gatewayPatientId,
      patientFirstName,
      patientLastName,
      patientDob,
      payerId,
      payerName,
      memberId,
      providerNpi,
      serviceDate,
      serviceTypeCode,
    },
    response: {
      success: coverageStatus !== "Unknown",
      check_id: checkId,
      gateway_patient_id: gatewayPatientId,
      patient_id: gatewayPatientId,
      coverage_status: coverageStatus,
      plan_name: planName,
      plan_type: planType,
      network_status: networkStatus,
      effective_date: effectiveDate,
      termination_date: terminationDate,
      group_number: groupNumber,
      confidence_score: confidenceScore,
      response_time_seconds: responseTimeSeconds,
      channel_used: "n8n Master Gateway",
      prior_auth_required: priorAuthRequired,
      requires_human_review: requiresHumanReview,
      flags,
    },
  };
}

const ELIGIBILITY_HISTORY = [
  {
    id: "EL-03891",
    subscriberId: "subscriber-sarah-mitchell",
    clientId: "client-demo",
    providerId: "seed-provider-demo-001",
    subscriberName: "Sarah J. Mitchell",
    payer: "UnitedHealthcare",
    memberId: "UHC-884720193",
    providerNpi: "1760421357",
    serviceDate: "2026-03-01",
    coverageStatus: "Active",
    planName: "Choice Plus PPO",
    planType: "PPO",
    networkStatus: "In Network",
    effectiveDate: "2025-01-01",
    terminationDate: null,
    deductibleIndividualTotal: 1500,
    deductibleIndividualMet: 900,
    oopMaxIndividual: 4500,
    copayPcp: 30,
    copaySpecialist: 55,
    coinsuranceIn: 20,
    confidenceScore: 94,
    flagsJson: JSON.stringify([
      "Coverage active for professional office visit",
      "Prior authorization recommended before advanced imaging scheduling",
    ]),
    requiresHumanReview: false,
    rawResponseJson: JSON.stringify(
      buildGatewayResponse({
        checkId: "EV-20260301-0001",
        gatewayPatientId: "PT-10001",
        submissionType: "manual",
        patientFirstName: "Sarah",
        patientLastName: "Mitchell",
        patientDob: "1985-03-14",
        payerId: "87726",
        payerName: "UnitedHealthcare",
        memberId: "UHC-884720193",
        providerNpi: "1760421357",
        serviceDate: "2026-03-01",
        coverageStatus: "Active",
        planName: "Choice Plus PPO",
        planType: "PPO",
        networkStatus: "In Network",
        effectiveDate: "2025-01-01",
        terminationDate: null,
        groupNumber: "GRP-44821",
        confidenceScore: 94,
        responseTimeSeconds: 3.2,
        priorAuthRequired: true,
        requiresHumanReview: false,
        flags: [
          "Coverage active for professional office visit",
          "Prior authorization recommended before advanced imaging scheduling",
        ],
      })
    ),
    channelUsed: "n8n Master Gateway",
    responseTimeSeconds: 3.2,
    verifiedBy: "Dana Kim",
    createdAt: new Date("2026-03-01T09:14:00Z"),
  },
  {
    id: "EL-03890",
    subscriberId: "subscriber-james-holloway",
    clientId: "client-demo",
    providerId: "seed-provider-demo-002",
    subscriberName: "James R. Holloway",
    payer: "Aetna",
    memberId: "AETNA-562901847",
    providerNpi: "1992846711",
    serviceDate: "2026-03-01",
    coverageStatus: "Active",
    planName: "Open Choice POS",
    planType: "POS",
    networkStatus: "In Network",
    effectiveDate: "2025-02-01",
    terminationDate: null,
    deductibleIndividualTotal: 1000,
    deductibleIndividualMet: 1000,
    oopMaxIndividual: 3500,
    copayPcp: 25,
    copaySpecialist: 45,
    coinsuranceIn: 10,
    confidenceScore: 91,
    flagsJson: JSON.stringify([
      "Converted to prior authorization case",
      "No financial barrier detected for planned orthopedic consult",
    ]),
    requiresHumanReview: false,
    rawResponseJson: JSON.stringify({
      ...buildGatewayResponse({
        checkId: "EV-20260301-0002",
        gatewayPatientId: "PT-10002",
        submissionType: "manual",
        patientFirstName: "James",
        patientLastName: "Holloway",
        patientDob: "1971-07-22",
        payerId: "60054",
        payerName: "Aetna",
        memberId: "AETNA-562901847",
        providerNpi: "1992846711",
        serviceDate: "2026-03-01",
        coverageStatus: "Active",
        planName: "Open Choice POS",
        planType: "POS",
        networkStatus: "In Network",
        effectiveDate: "2025-02-01",
        terminationDate: null,
        groupNumber: "GRP-77334",
        confidenceScore: 91,
        responseTimeSeconds: 1.8,
        priorAuthRequired: false,
        requiresHumanReview: false,
        flags: [
          "Converted to prior authorization case",
          "No financial barrier detected for planned orthopedic consult",
        ],
      }),
      convertedToPa: true,
    }),
    channelUsed: "n8n Master Gateway",
    responseTimeSeconds: 1.8,
    verifiedBy: "Drew Okafor",
    createdAt: new Date("2026-03-01T08:55:00Z"),
  },
  {
    id: "EL-03889",
    subscriberId: "subscriber-samuel-mitchell",
    clientId: "client-demo",
    providerId: "seed-provider-demo-003",
    subscriberName: "Samuel Mitchell",
    payer: "Cigna",
    memberId: "CIG-338881234",
    providerNpi: "1881762094",
    serviceDate: "2026-03-01",
    coverageStatus: "Unknown",
    planName: "Cigna Connect HMO",
    planType: "HMO",
    networkStatus: "Pending Verification",
    effectiveDate: "2025-01-15",
    terminationDate: null,
    deductibleIndividualTotal: 2000,
    deductibleIndividualMet: 600,
    oopMaxIndividual: 5000,
    copayPcp: 40,
    copaySpecialist: 70,
    coinsuranceIn: 30,
    confidenceScore: 58,
    flagsJson: JSON.stringify([
      "Eligibility could not be fully confirmed",
      "Member demographics should be verified by staff before scheduling",
    ]),
    requiresHumanReview: true,
    rawResponseJson: JSON.stringify(
      buildGatewayResponse({
        checkId: "EV-20260301-0003",
        gatewayPatientId: "PT-10003",
        submissionType: "ocr",
        patientFirstName: "Samuel",
        patientLastName: "Mitchell",
        patientDob: "1978-09-20",
        payerId: "62308",
        payerName: "Cigna",
        memberId: "CIG-338881234",
        providerNpi: "1881762094",
        serviceDate: "2026-03-01",
        coverageStatus: "Unknown",
        planName: "Cigna Connect HMO",
        planType: "HMO",
        networkStatus: "Pending Verification",
        effectiveDate: "2025-01-15",
        terminationDate: null,
        groupNumber: "GRP-77001",
        confidenceScore: 58,
        responseTimeSeconds: 4.1,
        priorAuthRequired: true,
        requiresHumanReview: true,
        flags: [
          "Eligibility could not be fully confirmed",
          "Member demographics should be verified by staff before scheduling",
        ],
      })
    ),
    channelUsed: "n8n Master Gateway",
    responseTimeSeconds: 4.1,
    verifiedBy: "Sam Torres",
    createdAt: new Date("2026-03-01T08:30:00Z"),
  },
  {
    id: "EL-03888",
    subscriberId: "subscriber-linda-patel",
    clientId: "client-demo",
    providerId: "seed-provider-demo-001",
    subscriberName: "Linda K. Patel",
    payer: "Blue Cross Blue Shield",
    memberId: "BCBS-774930281",
    providerNpi: "1760421357",
    serviceDate: "2026-03-01",
    coverageStatus: "Active",
    planName: "Blue Advantage PPO",
    planType: "PPO",
    networkStatus: "In Network",
    effectiveDate: "2024-11-01",
    terminationDate: null,
    deductibleIndividualTotal: 2000,
    deductibleIndividualMet: 400,
    oopMaxIndividual: 6000,
    copayPcp: 35,
    copaySpecialist: 60,
    coinsuranceIn: 20,
    confidenceScore: 88,
    flagsJson: JSON.stringify([
      "Behavioral health outpatient visits covered",
      "No prior authorization required for office follow-up",
    ]),
    requiresHumanReview: false,
    rawResponseJson: JSON.stringify(
      buildGatewayResponse({
        checkId: "EV-20260301-0004",
        gatewayPatientId: "PT-10004",
        submissionType: "emr",
        patientFirstName: "Linda",
        patientLastName: "Patel",
        patientDob: "1990-11-30",
        payerId: "00630",
        payerName: "Blue Cross Blue Shield",
        memberId: "BCBS-774930281",
        providerNpi: "1760421357",
        serviceDate: "2026-03-01",
        coverageStatus: "Active",
        planName: "Blue Advantage PPO",
        planType: "PPO",
        networkStatus: "In Network",
        effectiveDate: "2024-11-01",
        terminationDate: null,
        groupNumber: "GRP-22019",
        confidenceScore: 88,
        responseTimeSeconds: 1.1,
        priorAuthRequired: false,
        requiresHumanReview: false,
        flags: [
          "Behavioral health outpatient visits covered",
          "No prior authorization required for office follow-up",
        ],
      })
    ),
    channelUsed: "n8n Master Gateway",
    responseTimeSeconds: 1.1,
    verifiedBy: "Priya Mehta",
    createdAt: new Date("2026-03-01T08:10:00Z"),
  },
  {
    id: "EL-03887",
    subscriberId: "subscriber-sarah-mitchell",
    clientId: "client-sunrise-family-clinic",
    providerId: "seed-provider-sunrise-001",
    subscriberName: "Marcus A. Thompson",
    payer: "Medicare",
    memberId: "MBI-4EG9-UA8-YK72",
    providerNpi: "1992846711",
    serviceDate: "2026-02-28",
    coverageStatus: "Active",
    planName: "Original Medicare Part B",
    planType: "Government",
    networkStatus: "National",
    effectiveDate: "2024-07-01",
    terminationDate: null,
    deductibleIndividualTotal: 240,
    deductibleIndividualMet: 240,
    oopMaxIndividual: null,
    copayPcp: 20,
    copaySpecialist: 20,
    coinsuranceIn: 20,
    confidenceScore: 96,
    flagsJson: JSON.stringify([
      "Converted to prior authorization case",
      "Specialty procedure requires payer-specific intake packet",
    ]),
    requiresHumanReview: false,
    rawResponseJson: JSON.stringify({
      ...buildGatewayResponse({
        checkId: "EV-20260228-0005",
        gatewayPatientId: "PT-10005",
        submissionType: "bulk",
        patientFirstName: "Marcus",
        patientLastName: "Thompson",
        patientDob: "1964-05-19",
        payerId: "MBI",
        payerName: "Medicare",
        memberId: "MBI-4EG9-UA8-YK72",
        providerNpi: "1992846711",
        serviceDate: "2026-02-28",
        coverageStatus: "Active",
        planName: "Original Medicare Part B",
        planType: "Government",
        networkStatus: "National",
        effectiveDate: "2024-07-01",
        terminationDate: null,
        groupNumber: "MEDICARE-A",
        confidenceScore: 96,
        responseTimeSeconds: 2.9,
        priorAuthRequired: true,
        requiresHumanReview: false,
        flags: [
          "Converted to prior authorization case",
          "Specialty procedure requires payer-specific intake packet",
        ],
      }),
      convertedToPa: true,
    }),
    channelUsed: "n8n Master Gateway",
    responseTimeSeconds: 2.9,
    verifiedBy: "Dana Kim",
    createdAt: new Date("2026-02-28T17:45:00Z"),
  },
  {
    id: "EL-03886",
    subscriberId: "subscriber-james-holloway",
    clientId: "client-lakeview-orthopedics",
    providerId: "seed-provider-lakeview-002",
    subscriberName: "Emily R. Carson",
    payer: "Cigna",
    memberId: "CIG-338821904",
    providerNpi: "1881762094",
    serviceDate: "2026-02-28",
    coverageStatus: "Inactive",
    planName: "Cigna Connect EPO",
    planType: "EPO",
    networkStatus: "Out of Network",
    effectiveDate: "2025-01-01",
    terminationDate: "2026-02-15",
    deductibleIndividualTotal: 2500,
    deductibleIndividualMet: 2500,
    oopMaxIndividual: 6500,
    copayPcp: 45,
    copaySpecialist: 75,
    coinsuranceIn: 40,
    confidenceScore: 82,
    flagsJson: JSON.stringify([
      "Coverage terminated before requested service date",
      "Patient should be contacted for updated insurance card",
    ]),
    requiresHumanReview: false,
    rawResponseJson: JSON.stringify(
      buildGatewayResponse({
        checkId: "EV-20260228-0006",
        gatewayPatientId: "PT-10006",
        submissionType: "manual",
        patientFirstName: "Emily",
        patientLastName: "Carson",
        patientDob: "1989-12-09",
        payerId: "62308",
        payerName: "Cigna",
        memberId: "CIG-338821904",
        providerNpi: "1881762094",
        serviceDate: "2026-02-28",
        coverageStatus: "Inactive",
        planName: "Cigna Connect EPO",
        planType: "EPO",
        networkStatus: "Out of Network",
        effectiveDate: "2025-01-01",
        terminationDate: "2026-02-15",
        groupNumber: "GRP-66519",
        confidenceScore: 82,
        responseTimeSeconds: 5.6,
        priorAuthRequired: null,
        requiresHumanReview: false,
        flags: [
          "Coverage terminated before requested service date",
          "Patient should be contacted for updated insurance card",
        ],
      })
    ),
    channelUsed: "n8n Master Gateway",
    responseTimeSeconds: 5.6,
    verifiedBy: "Drew Okafor",
    createdAt: new Date("2026-02-28T16:20:00Z"),
  },
];

export async function seedEligibilityHistory(prisma) {
  for (const historyRecord of ELIGIBILITY_HISTORY) {
    await prisma.eligibilityHistory.upsert({
      where: { id: historyRecord.id },
      update: historyRecord,
      create: historyRecord,
    });
  }

  console.log(`✅ Seeded ${ELIGIBILITY_HISTORY.length} eligibility history records`);
}
