const ELIGIBILITY_HISTORY = [
  {
    id: "elig-history-03891",
    subscriberId: "seed-sub-sarah-mitchell",
    clientId: "client-sunrise-family-clinic",
    providerId: "seed-provider-sunrise-001",
    subscriberName: "Sarah J. Mitchell",
    payer: "UnitedHealthcare",
    memberId: "UHC-884720193",
    providerNpi: "1760421357",
    serviceDate: "2026-03-01",
    coverageStatus: "Active",
    planName: "Choice Plus",
    planType: "PPO",
    networkStatus: "In Network",
    effectiveDate: "2025-01-01",
    terminationDate: null,
    deductibleIndividualTotal: 1500,
    deductibleIndividualMet: 900,
    oopMaxIndividual: 4500,
    copayPcp: 30,
    copaySpecialist: 55,
    coinsuranceIn: 20,
    confidenceScore: 94,
    flagsJson: JSON.stringify([]),
    requiresHumanReview: false,
    rawResponseJson: JSON.stringify({ convertedToPa: false }),
    channelUsed: "Availity",
    responseTimeSeconds: 3.2,
    verifiedBy: "Dana Kim",
    createdAt: new Date("2026-03-01T09:14:00Z"),
  },
  {
    id: "elig-history-03890",
    subscriberId: "seed-sub-james-holloway",
    clientId: "client-lakeview-orthopedics",
    providerId: "seed-provider-lakeview-001",
    subscriberName: "James R. Holloway",
    payer: "Aetna",
    memberId: "AETNA-562901847",
    providerNpi: "1992846711",
    serviceDate: "2026-03-01",
    coverageStatus: "Active",
    planName: "Open Choice",
    planType: "POS",
    networkStatus: "In Network",
    effectiveDate: "2025-02-01",
    terminationDate: null,
    deductibleIndividualTotal: 1000,
    deductibleIndividualMet: 1000,
    oopMaxIndividual: 3500,
    copayPcp: 25,
    copaySpecialist: 45,
    coinsuranceIn: 10,
    confidenceScore: 91,
    flagsJson: JSON.stringify(["Converted to prior authorization case"]),
    requiresHumanReview: false,
    rawResponseJson: JSON.stringify({ convertedToPa: true }),
    channelUsed: "Direct Payer API",
    responseTimeSeconds: 1.8,
    verifiedBy: "Drew Okafor",
    createdAt: new Date("2026-03-01T08:55:00Z"),
  },
  {
    id: "elig-history-03889",
    subscriberId: "seed-sub-robert-sanchez",
    clientId: "client-metro-mental-health-associates",
    providerId: "seed-provider-metro-001",
    subscriberName: "Robert T. Sanchez",
    payer: "Medicaid",
    memberId: "MCD-112984732",
    providerNpi: "1881762094",
    serviceDate: "2026-03-01",
    coverageStatus: "Unknown",
    planName: "State Managed Medicaid",
    planType: "HMO",
    networkStatus: "Pending",
    effectiveDate: "2025-01-15",
    terminationDate: null,
    deductibleIndividualTotal: 0,
    deductibleIndividualMet: 0,
    oopMaxIndividual: 0,
    copayPcp: 0,
    copaySpecialist: 0,
    coinsuranceIn: 0,
    confidenceScore: 58,
    flagsJson: JSON.stringify(["Eligibility could not be fully confirmed"]),
    requiresHumanReview: true,
    rawResponseJson: JSON.stringify({ convertedToPa: false }),
    channelUsed: "Availity",
    responseTimeSeconds: 4.1,
    verifiedBy: "Sam Torres",
    createdAt: new Date("2026-03-01T08:30:00Z"),
  },
  {
    id: "elig-history-03888",
    subscriberId: "seed-sub-linda-patel",
    clientId: "client-sunrise-family-clinic",
    providerId: "seed-provider-sunrise-002",
    subscriberName: "Linda K. Patel",
    payer: "Blue Cross Blue Shield",
    memberId: "BCBS-774930281",
    providerNpi: "1760421357",
    serviceDate: "2026-03-01",
    coverageStatus: "Active",
    planName: "Blue Advantage",
    planType: "PPO",
    networkStatus: "In Network",
    effectiveDate: "2024-11-01",
    terminationDate: null,
    deductibleIndividualTotal: 2000,
    deductibleIndividualMet: 400,
    oopMaxIndividual: 6000,
    copayPcp: 35,
    copaySpecialist: 60,
    coinsuranceIn: 20,
    confidenceScore: 88,
    flagsJson: JSON.stringify([]),
    requiresHumanReview: false,
    rawResponseJson: JSON.stringify({ convertedToPa: false }),
    channelUsed: "EMR Integration",
    responseTimeSeconds: 0.95,
    verifiedBy: "Priya Mehta",
    createdAt: new Date("2026-03-01T08:10:00Z"),
  },
  {
    id: "elig-history-03887",
    subscriberId: "seed-sub-marcus-thompson",
    clientId: "client-lakeview-orthopedics",
    providerId: "seed-provider-lakeview-002",
    subscriberName: "Marcus A. Thompson",
    payer: "Medicare",
    memberId: "MBI-4EG9-UA8-YK72",
    providerNpi: "1992846711",
    serviceDate: "2026-02-28",
    coverageStatus: "Active",
    planName: "Original Medicare",
    planType: "Government",
    networkStatus: "National",
    effectiveDate: "2024-07-01",
    terminationDate: null,
    deductibleIndividualTotal: 240,
    deductibleIndividualMet: 240,
    oopMaxIndividual: null,
    copayPcp: 20,
    copaySpecialist: 20,
    coinsuranceIn: 20,
    confidenceScore: 96,
    flagsJson: JSON.stringify(["Converted to prior authorization case"]),
    requiresHumanReview: false,
    rawResponseJson: JSON.stringify({ convertedToPa: true }),
    channelUsed: "Availity",
    responseTimeSeconds: 2.9,
    verifiedBy: "Dana Kim",
    createdAt: new Date("2026-02-28T17:45:00Z"),
  },
  {
    id: "elig-history-03886",
    subscriberId: "seed-sub-emily-carson",
    clientId: "client-metro-mental-health-associates",
    providerId: "seed-provider-metro-002",
    subscriberName: "Emily R. Carson",
    payer: "Cigna",
    memberId: "CIG-338821904",
    providerNpi: "1881762094",
    serviceDate: "2026-02-28",
    coverageStatus: "Inactive",
    planName: "Cigna Connect",
    planType: "EPO",
    networkStatus: "Out of Network",
    effectiveDate: "2025-01-01",
    terminationDate: "2026-02-15",
    deductibleIndividualTotal: 2500,
    deductibleIndividualMet: 2500,
    oopMaxIndividual: 6500,
    copayPcp: 45,
    copaySpecialist: 75,
    coinsuranceIn: 40,
    confidenceScore: 82,
    flagsJson: JSON.stringify(["Coverage terminated before requested service date"]),
    requiresHumanReview: false,
    rawResponseJson: JSON.stringify({ convertedToPa: false }),
    channelUsed: "Portal Automation",
    responseTimeSeconds: 12.4,
    verifiedBy: "Drew Okafor",
    createdAt: new Date("2026-02-28T16:20:00Z"),
  },
];

export async function seedEligibilityHistory(prisma) {
  for (const historyRecord of ELIGIBILITY_HISTORY) {
    await prisma.eligibilityHistory.upsert({
      where: { id: historyRecord.id },
      update: historyRecord,
      create: historyRecord,
    });
  }

  console.log(`✅ Seeded ${ELIGIBILITY_HISTORY.length} eligibility history records`);
}
