/**
 * seeds/patients.js
 * Seeds sample patients and their insurance policies
 */

const PATIENTS = [
  {
    id: "patient-001",
    clientId: "client-demo",
    firstName: "Sarah",
    lastName: "Mitchell",
    middleName: "Anne",
    dob: new Date("1985-03-15"),
    gender: "Female",
    ssn: "512-48-1024",
    phone: "(555) 123-4567",
    email: "sarah.mitchell@email.com",
    address: "123 Oak Street",
    city: "Austin",
    state: "TX",
    zip: "78701",
  },
  {
    id: "patient-002",
    clientId: "client-demo",
    firstName: "Michael",
    lastName: "Johnson",
    middleName: "Ray",
    dob: new Date("1978-07-22"),
    gender: "Male",
    ssn: "407-61-2388",
    phone: "(555) 234-5678",
    email: "m.johnson@email.com",
    address: "456 Maple Avenue",
    city: "Austin",
    state: "TX",
    zip: "78702",
  },
  {
    id: "patient-003",
    clientId: "client-demo",
    firstName: "Emily",
    lastName: "Chen",
    middleName: "Wei",
    dob: new Date("1992-11-08"),
    gender: "Female",
    ssn: "628-74-1913",
    phone: "(555) 345-6789",
    email: "emily.chen@email.com",
    address: "789 Pine Road",
    city: "Round Rock",
    state: "TX",
    zip: "78664",
  },
  {
    id: "patient-004",
    clientId: "client-sunrise-family-clinic",
    firstName: "Robert",
    lastName: "Garcia",
    middleName: "Luis",
    dob: new Date("1965-01-30"),
    gender: "Male",
    ssn: "389-22-5806",
    phone: "(555) 456-7890",
    email: "r.garcia@email.com",
    address: "321 Cedar Lane",
    city: "Austin",
    state: "TX",
    zip: "78703",
  },
  {
    id: "patient-005",
    clientId: "client-sunrise-family-clinic",
    firstName: "Amanda",
    lastName: "Williams",
    middleName: "Rose",
    dob: new Date("1988-09-12"),
    gender: "Female",
    ssn: "476-35-8201",
    phone: "(555) 567-8901",
    email: "amanda.w@email.com",
    address: "654 Birch Street",
    city: "Pflugerville",
    state: "TX",
    zip: "78660",
  },
  {
    id: "patient-006",
    clientId: "client-sunrise-family-clinic",
    firstName: "David",
    lastName: "Brown",
    middleName: "Allen",
    dob: new Date("1972-04-25"),
    gender: "Male",
    ssn: "583-14-6729",
    phone: "(555) 678-9012",
    email: "david.brown@email.com",
    address: "987 Elm Drive",
    city: "Austin",
    state: "TX",
    zip: "78704",
  },
  {
    id: "patient-007",
    clientId: "client-lakeview-orthopedics",
    firstName: "Jennifer",
    lastName: "Martinez",
    middleName: "Sofia",
    dob: new Date("1995-12-03"),
    gender: "Female",
    ssn: "691-28-4475",
    phone: "(555) 789-0123",
    email: "j.martinez@email.com",
    address: "246 Willow Way",
    city: "Cedar Park",
    state: "TX",
    zip: "78613",
  },
  {
    id: "patient-008",
    clientId: "client-lakeview-orthopedics",
    firstName: "James",
    lastName: "Anderson",
    middleName: "Patrick",
    dob: new Date("1958-06-17"),
    gender: "Male",
    ssn: "734-89-2401",
    phone: "(555) 890-1234",
    email: "james.a@email.com",
    address: "135 Spruce Court",
    city: "Austin",
    state: "TX",
    zip: "78705",
  },
  {
    id: "patient-009",
    clientId: "client-lakeview-orthopedics",
    firstName: "Lisa",
    lastName: "Taylor",
    middleName: "Marie",
    dob: new Date("1983-02-28"),
    gender: "Female",
    ssn: "445-73-6612",
    phone: "(555) 901-2345",
    email: "lisa.taylor@email.com",
    address: "864 Aspen Boulevard",
    city: "Lakeway",
    state: "TX",
    zip: "78734",
  },
  {
    id: "patient-010",
    clientId: "client-metro-mental-health-associates",
    firstName: "Christopher",
    lastName: "Lee",
    middleName: "Daniel",
    dob: new Date("1990-08-19"),
    gender: "Male",
    ssn: "554-21-9037",
    phone: "(555) 012-3456",
    email: "chris.lee@email.com",
    address: "579 Redwood Circle",
    city: "Austin",
    state: "TX",
    zip: "78706",
  },
  {
    id: "patient-011",
    clientId: "client-metro-mental-health-associates",
    firstName: "Monica",
    lastName: "Reyes",
    middleName: "Elena",
    dob: new Date("1987-05-09"),
    gender: "Female",
    ssn: "614-32-7805",
    phone: "(555) 147-2580",
    email: "monica.reyes@email.com",
    address: "412 Juniper Street",
    city: "Austin",
    state: "TX",
    zip: "78741",
  },
  {
    id: "patient-012",
    clientId: "client-metro-mental-health-associates",
    firstName: "Nathan",
    lastName: "Brooks",
    middleName: "Cole",
    dob: new Date("1993-10-27"),
    gender: "Male",
    ssn: "722-58-1146",
    phone: "(555) 258-3691",
    email: "nathan.brooks@email.com",
    address: "908 Horizon Trail",
    city: "Austin",
    state: "TX",
    zip: "78745",
  },
];

const INSURANCE_POLICIES = [
  // Patient 001 - Primary and Secondary
  {
    id: "policy-001",
    patientId: "patient-001",
    policyType: "PRIMARY",
    payerName: "UnitedHealthcare",
    payerId: "87726",
    memberId: "UHC-884720193",
    groupNumber: "GRP-44821",
    subscriberName: "Sarah A. Mitchell",
    subscriberDob: new Date("1985-03-15"),
    subscriberRelationship: "Self",
    planName: "Choice Plus PPO",
    planType: "PPO",
    effectiveDate: new Date("2024-01-01"),
    terminationDate: new Date("2026-12-31"),
    rxBin: "610014",
    rxPcn: "OHCARD",
    rxGroup: "OHRX",
    copayPcp: 25,
    copaySpecialist: 50,
  },
  {
    id: "policy-002",
    patientId: "patient-001",
    policyType: "SECONDARY",
    payerName: "Aetna",
    payerId: "60054",
    memberId: "AET-W882914",
    groupNumber: "GRP-99127",
    subscriberName: "John Mitchell",
    subscriberDob: new Date("1982-04-09"),
    subscriberRelationship: "Spouse",
    planName: "Open Access Managed Choice",
    planType: "POS",
    effectiveDate: new Date("2024-01-01"),
    terminationDate: new Date("2026-12-31"),
    rxBin: "610502",
    rxPcn: "AETNA",
    rxGroup: "ADVRX",
    copayPcp: 30,
    copaySpecialist: 55,
  },
  // Patient 002 - Primary only (Medicare)
  {
    id: "policy-003",
    patientId: "patient-002",
    policyType: "PRIMARY",
    payerName: "Medicare",
    payerId: "MEDICARE",
    memberId: "1EG4-TE5-MK72",
    groupNumber: "MEDB-2023",
    subscriberName: "Michael R. Johnson",
    subscriberDob: new Date("1978-07-22"),
    subscriberRelationship: "Self",
    planName: "Medicare Part B",
    planType: "Medicare",
    effectiveDate: new Date("2023-07-01"),
    terminationDate: new Date("2026-12-31"),
    rxBin: "004336",
    rxPcn: "MEDDADV",
    rxGroup: "MEDICARE",
    copayPcp: 20,
    copaySpecialist: 20,
  },
  // Patient 003 - Primary
  {
    id: "policy-004",
    patientId: "patient-003",
    policyType: "PRIMARY",
    payerName: "Blue Cross Blue Shield",
    payerId: "BCBS",
    memberId: "BCBS-XYZ789456",
    groupNumber: "GRP-TECH2024",
    subscriberName: "Emily W. Chen",
    subscriberDob: new Date("1992-11-08"),
    subscriberRelationship: "Self",
    planName: "Blue PPO Silver",
    planType: "PPO",
    effectiveDate: new Date("2024-01-01"),
    terminationDate: new Date("2026-12-31"),
    rxBin: "004336",
    rxPcn: "ADV",
    rxGroup: "BCBSRX",
    copayPcp: 20,
    copaySpecialist: 40,
  },
  // Patient 004 - Primary and Secondary (Medicare + Supplement)
  {
    id: "policy-005",
    patientId: "patient-004",
    policyType: "PRIMARY",
    payerName: "Medicare",
    payerId: "MEDICARE",
    memberId: "1AB2-CD3-EF45",
    groupNumber: "MEDAB-2020",
    subscriberName: "Robert L. Garcia",
    subscriberDob: new Date("1965-01-30"),
    subscriberRelationship: "Self",
    planName: "Medicare Part A & B",
    planType: "Medicare",
    effectiveDate: new Date("2020-02-01"),
    terminationDate: new Date("2026-12-31"),
    rxBin: "004336",
    rxPcn: "MEDICARE",
    rxGroup: "PARTD-A",
    copayPcp: 20,
    copaySpecialist: 20,
  },
  {
    id: "policy-006",
    patientId: "patient-004",
    policyType: "SECONDARY",
    payerName: "AARP Medicare Supplement",
    payerId: "AARPMS",
    memberId: "AARP-445566778",
    groupNumber: "SUPP-G2020",
    subscriberName: "Robert L. Garcia",
    subscriberDob: new Date("1965-01-30"),
    subscriberRelationship: "Self",
    planName: "Plan G",
    planType: "Medicare Supplement",
    effectiveDate: new Date("2020-02-01"),
    terminationDate: new Date("2026-12-31"),
    rxBin: "610097",
    rxPcn: "AARP",
    rxGroup: "SUPPLAN",
    copayPcp: 0,
    copaySpecialist: 0,
  },
  // Patient 005 - Primary (HMO)
  {
    id: "policy-007",
    patientId: "patient-005",
    policyType: "PRIMARY",
    payerName: "Cigna",
    payerId: "62308",
    memberId: "CIG-998877665",
    groupNumber: "GRP-EMP2024",
    subscriberName: "Amanda R. Williams",
    subscriberDob: new Date("1988-09-12"),
    subscriberRelationship: "Self",
    planName: "Cigna Connect HMO",
    planType: "HMO",
    effectiveDate: new Date("2024-01-01"),
    terminationDate: new Date("2026-12-31"),
    rxBin: "017010",
    rxPcn: "CIGRX",
    rxGroup: "CIGNAHMO",
    copayPcp: 15,
    copaySpecialist: 35,
  },
  // Patient 006 - Primary
  {
    id: "policy-008",
    patientId: "patient-006",
    policyType: "PRIMARY",
    payerName: "Humana",
    payerId: "61101",
    memberId: "HUM-112233445",
    groupNumber: "GRP-CORP100",
    subscriberName: "David Brown",
    subscriberDob: new Date("1972-04-25"),
    subscriberRelationship: "Self",
    planName: "Humana Gold Plus",
    planType: "PPO",
    effectiveDate: new Date("2023-06-01"),
    terminationDate: new Date("2026-12-31"),
    rxBin: "610649",
    rxPcn: "HUMANA",
    rxGroup: "HUMGOLD",
    copayPcp: 30,
    copaySpecialist: 55,
  },
  // Patient 007 - Primary (Medicaid)
  {
    id: "policy-009",
    patientId: "patient-007",
    policyType: "PRIMARY",
    payerName: "Texas Medicaid",
    payerId: "TXMED",
    memberId: "TXM-887766554",
    groupNumber: "STAR-2024",
    subscriberName: "Jennifer S. Martinez",
    subscriberDob: new Date("1995-12-03"),
    subscriberRelationship: "Self",
    planName: "STAR Health",
    planType: "Medicaid Managed Care",
    effectiveDate: new Date("2024-01-01"),
    terminationDate: new Date("2026-12-31"),
    rxBin: "014203",
    rxPcn: "MEDICAID",
    rxGroup: "TXSTAR",
    copayPcp: 0,
    copaySpecialist: 0,
  },
  // Patient 008 - Primary and Secondary
  {
    id: "policy-010",
    patientId: "patient-008",
    policyType: "PRIMARY",
    payerName: "Medicare",
    payerId: "MEDICARE",
    memberId: "1XY9-ZW8-VU76",
    groupNumber: "MEDAB-2018",
    subscriberName: "James P. Anderson",
    subscriberDob: new Date("1958-06-17"),
    subscriberRelationship: "Self",
    planName: "Medicare Part A & B",
    planType: "Medicare",
    effectiveDate: new Date("2018-07-01"),
    terminationDate: new Date("2026-12-31"),
    rxBin: "004336",
    rxPcn: "MEDICARE",
    rxGroup: "PARTD-B",
    copayPcp: 20,
    copaySpecialist: 20,
  },
  {
    id: "policy-011",
    patientId: "patient-008",
    policyType: "SECONDARY",
    payerName: "Humana Medicare Advantage",
    payerId: "61101",
    memberId: "HMA-334455667",
    groupNumber: "HMA-2024",
    subscriberName: "James P. Anderson",
    subscriberDob: new Date("1958-06-17"),
    subscriberRelationship: "Self",
    planName: "Humana Gold Plus HMO",
    planType: "Medicare Advantage",
    effectiveDate: new Date("2024-01-01"),
    terminationDate: new Date("2026-12-31"),
    rxBin: "610649",
    rxPcn: "HUMANA",
    rxGroup: "HMAGOLD",
    copayPcp: 10,
    copaySpecialist: 35,
  },
  // Patient 009 - Primary
  {
    id: "policy-012",
    patientId: "patient-009",
    policyType: "PRIMARY",
    payerName: "Aetna",
    payerId: "60054",
    memberId: "AET-556677889",
    groupNumber: "GRP-FIN500",
    subscriberName: "Lisa Taylor",
    subscriberDob: new Date("1983-02-28"),
    subscriberRelationship: "Self",
    planName: "Aetna Choice POS II",
    planType: "POS",
    effectiveDate: new Date("2024-01-01"),
    terminationDate: new Date("2026-12-31"),
    rxBin: "004336",
    rxPcn: "MEDDADV",
    rxGroup: "AETPOS",
    copayPcp: 25,
    copaySpecialist: 45,
  },
  // Patient 010 - Primary (HDHP with HSA)
  {
    id: "policy-013",
    patientId: "patient-010",
    policyType: "PRIMARY",
    payerName: "UnitedHealthcare",
    payerId: "87726",
    memberId: "UHC-223344556",
    groupNumber: "GRP-STARTUP",
    subscriberName: "Christopher Lee",
    subscriberDob: new Date("1990-08-19"),
    subscriberRelationship: "Self",
    planName: "UHC HDHP Bronze",
    planType: "HDHP",
    effectiveDate: new Date("2024-01-01"),
    terminationDate: new Date("2026-12-31"),
    rxBin: "610014",
    rxPcn: "OHCARD",
    rxGroup: "UHCBRONZE",
    copayPcp: 35,
    copaySpecialist: 65,
  },
  // Patient 011 - Primary
  {
    id: "policy-014",
    patientId: "patient-011",
    policyType: "PRIMARY",
    payerName: "Blue Cross Blue Shield",
    payerId: "BCBS",
    memberId: "BCBS-445512309",
    groupNumber: "GRP-BH2024",
    subscriberName: "Monica E. Reyes",
    subscriberDob: new Date("1987-05-09"),
    subscriberRelationship: "Self",
    planName: "Blue Essentials PPO",
    planType: "PPO",
    effectiveDate: new Date("2024-01-01"),
    terminationDate: new Date("2026-12-31"),
    rxBin: "004336",
    rxPcn: "ADV",
    rxGroup: "BCBSESS",
    copayPcp: 25,
    copaySpecialist: 50,
  },
  // Patient 012 - Primary
  {
    id: "policy-015",
    patientId: "patient-012",
    policyType: "PRIMARY",
    payerName: "Aetna",
    payerId: "60054",
    memberId: "AET-774421580",
    groupNumber: "GRP-MH300",
    subscriberName: "Nathan Brooks",
    subscriberDob: new Date("1993-10-27"),
    subscriberRelationship: "Self",
    planName: "Aetna Signature Administrators PPO",
    planType: "PPO",
    effectiveDate: new Date("2024-01-01"),
    terminationDate: new Date("2026-12-31"),
    rxBin: "610502",
    rxPcn: "AETNA",
    rxGroup: "AETSIGN",
    copayPcp: 20,
    copaySpecialist: 45,
  },
];

export async function seedPatients(prisma) {
  for (const patient of PATIENTS) {
    await prisma.patient.upsert({
      where: { id: patient.id },
      update: patient,
      create: patient,
    });
  }

  console.log("✅ Created sample patients");

  for (const policy of INSURANCE_POLICIES) {
    await prisma.insurancePolicy.upsert({
      where: { id: policy.id },
      update: policy,
      create: policy,
    });
  }

  console.log("✅ Created sample insurance policies");
}
