/**
 * seeds/patients.js
 * Seeds sample patients and their insurance policies
 */

const PATIENTS = [
  {
    id: "patient-001",
    clientId: "client-demo",
    firstName: "Sarah",
    lastName: "Mitchell",
    middleName: "Anne",
    dob: new Date("1985-03-15"),
    gender: "Female",
    phone: "(555) 123-4567",
    email: "sarah.mitchell@email.com",
    address: "123 Oak Street",
    city: "Austin",
    state: "TX",
    zip: "78701",
  },
  {
    id: "patient-002",
    clientId: "client-demo",
    firstName: "Michael",
    lastName: "Johnson",
    dob: new Date("1978-07-22"),
    gender: "Male",
    phone: "(555) 234-5678",
    email: "m.johnson@email.com",
    address: "456 Maple Avenue",
    city: "Austin",
    state: "TX",
    zip: "78702",
  },
  {
    id: "patient-003",
    clientId: "client-demo",
    firstName: "Emily",
    lastName: "Chen",
    middleName: "Wei",
    dob: new Date("1992-11-08"),
    gender: "Female",
    phone: "(555) 345-6789",
    email: "emily.chen@email.com",
    address: "789 Pine Road",
    city: "Round Rock",
    state: "TX",
    zip: "78664",
  },
  {
    id: "patient-004",
    clientId: "client-demo",
    firstName: "Robert",
    lastName: "Garcia",
    dob: new Date("1965-01-30"),
    gender: "Male",
    phone: "(555) 456-7890",
    email: "r.garcia@email.com",
    address: "321 Cedar Lane",
    city: "Austin",
    state: "TX",
    zip: "78703",
  },
  {
    id: "patient-005",
    clientId: "client-demo",
    firstName: "Amanda",
    lastName: "Williams",
    middleName: "Rose",
    dob: new Date("1988-09-12"),
    gender: "Female",
    phone: "(555) 567-8901",
    email: "amanda.w@email.com",
    address: "654 Birch Street",
    city: "Pflugerville",
    state: "TX",
    zip: "78660",
  },
  {
    id: "patient-006",
    clientId: "client-demo",
    firstName: "David",
    lastName: "Brown",
    dob: new Date("1972-04-25"),
    gender: "Male",
    phone: "(555) 678-9012",
    email: "david.brown@email.com",
    address: "987 Elm Drive",
    city: "Austin",
    state: "TX",
    zip: "78704",
  },
  {
    id: "patient-007",
    clientId: "client-demo",
    firstName: "Jennifer",
    lastName: "Martinez",
    dob: new Date("1995-12-03"),
    gender: "Female",
    phone: "(555) 789-0123",
    email: "j.martinez@email.com",
    address: "246 Willow Way",
    city: "Cedar Park",
    state: "TX",
    zip: "78613",
  },
  {
    id: "patient-008",
    clientId: "client-demo",
    firstName: "James",
    lastName: "Anderson",
    middleName: "Patrick",
    dob: new Date("1958-06-17"),
    gender: "Male",
    phone: "(555) 890-1234",
    email: "james.a@email.com",
    address: "135 Spruce Court",
    city: "Austin",
    state: "TX",
    zip: "78705",
  },
  {
    id: "patient-009",
    clientId: "client-demo",
    firstName: "Lisa",
    lastName: "Taylor",
    dob: new Date("1983-02-28"),
    gender: "Female",
    phone: "(555) 901-2345",
    email: "lisa.taylor@email.com",
    address: "864 Aspen Boulevard",
    city: "Lakeway",
    state: "TX",
    zip: "78734",
  },
  {
    id: "patient-010",
    clientId: "client-demo",
    firstName: "Christopher",
    lastName: "Lee",
    dob: new Date("1990-08-19"),
    gender: "Male",
    phone: "(555) 012-3456",
    email: "chris.lee@email.com",
    address: "579 Redwood Circle",
    city: "Austin",
    state: "TX",
    zip: "78706",
  },
];

const INSURANCE_POLICIES = [
  // Patient 001 - Primary and Secondary
  {
    id: "policy-001",
    patientId: "patient-001",
    policyType: "PRIMARY",
    payerName: "UnitedHealthcare",
    payerId: "87726",
    memberId: "UHC-884720193",
    groupNumber: "GRP-44821",
    subscriberName: "Sarah A. Mitchell",
    subscriberRelationship: "Self",
    planName: "Choice Plus PPO",
    planType: "PPO",
    effectiveDate: new Date("2024-01-01"),
    rxBin: "610014",
    rxPcn: "OHCARD",
    rxGroup: "OHRX",
    copayPcp: 25,
    copaySpecialist: 50,
  },
  {
    id: "policy-002",
    patientId: "patient-001",
    policyType: "SECONDARY",
    payerName: "Aetna",
    payerId: "60054",
    memberId: "AET-W882914",
    groupNumber: "GRP-99127",
    subscriberName: "John Mitchell",
    subscriberRelationship: "Spouse",
    planName: "Open Access Managed Choice",
    planType: "POS",
    effectiveDate: new Date("2024-01-01"),
  },
  // Patient 002 - Primary only (Medicare)
  {
    id: "policy-003",
    patientId: "patient-002",
    policyType: "PRIMARY",
    payerName: "Medicare",
    memberId: "1EG4-TE5-MK72",
    planName: "Medicare Part B",
    planType: "Medicare",
    effectiveDate: new Date("2023-07-01"),
  },
  // Patient 003 - Primary
  {
    id: "policy-004",
    patientId: "patient-003",
    policyType: "PRIMARY",
    payerName: "Blue Cross Blue Shield",
    payerId: "BCBS",
    memberId: "BCBS-XYZ789456",
    groupNumber: "GRP-TECH2024",
    subscriberName: "Emily W. Chen",
    subscriberRelationship: "Self",
    planName: "Blue PPO Silver",
    planType: "PPO",
    effectiveDate: new Date("2024-01-01"),
    rxBin: "004336",
    rxPcn: "ADV",
    copayPcp: 20,
    copaySpecialist: 40,
  },
  // Patient 004 - Primary and Secondary (Medicare + Supplement)
  {
    id: "policy-005",
    patientId: "patient-004",
    policyType: "PRIMARY",
    payerName: "Medicare",
    memberId: "1AB2-CD3-EF45",
    planName: "Medicare Part A & B",
    planType: "Medicare",
    effectiveDate: new Date("2020-02-01"),
  },
  {
    id: "policy-006",
    patientId: "patient-004",
    policyType: "SECONDARY",
    payerName: "AARP Medicare Supplement",
    memberId: "AARP-445566778",
    planName: "Plan G",
    planType: "Medicare Supplement",
    effectiveDate: new Date("2020-02-01"),
  },
  // Patient 005 - Primary (HMO)
  {
    id: "policy-007",
    patientId: "patient-005",
    policyType: "PRIMARY",
    payerName: "Cigna",
    payerId: "62308",
    memberId: "CIG-998877665",
    groupNumber: "GRP-EMP2024",
    subscriberName: "Amanda R. Williams",
    subscriberRelationship: "Self",
    planName: "Cigna Connect HMO",
    planType: "HMO",
    effectiveDate: new Date("2024-01-01"),
    copayPcp: 15,
    copaySpecialist: 35,
  },
  // Patient 006 - Primary
  {
    id: "policy-008",
    patientId: "patient-006",
    policyType: "PRIMARY",
    payerName: "Humana",
    payerId: "61101",
    memberId: "HUM-112233445",
    groupNumber: "GRP-CORP100",
    subscriberName: "David Brown",
    subscriberRelationship: "Self",
    planName: "Humana Gold Plus",
    planType: "PPO",
    effectiveDate: new Date("2023-06-01"),
    rxBin: "610649",
    rxPcn: "HUMANA",
    copayPcp: 30,
    copaySpecialist: 55,
  },
  // Patient 007 - Primary (Medicaid)
  {
    id: "policy-009",
    patientId: "patient-007",
    policyType: "PRIMARY",
    payerName: "Texas Medicaid",
    memberId: "TXM-887766554",
    planName: "STAR Health",
    planType: "Medicaid Managed Care",
    effectiveDate: new Date("2024-01-01"),
    copayPcp: 0,
    copaySpecialist: 0,
  },
  // Patient 008 - Primary and Secondary
  {
    id: "policy-010",
    patientId: "patient-008",
    policyType: "PRIMARY",
    payerName: "Medicare",
    memberId: "1XY9-ZW8-VU76",
    planName: "Medicare Part A & B",
    planType: "Medicare",
    effectiveDate: new Date("2018-07-01"),
  },
  {
    id: "policy-011",
    patientId: "patient-008",
    policyType: "SECONDARY",
    payerName: "Humana Medicare Advantage",
    payerId: "61101",
    memberId: "HMA-334455667",
    planName: "Humana Gold Plus HMO",
    planType: "Medicare Advantage",
    effectiveDate: new Date("2024-01-01"),
  },
  // Patient 009 - Primary
  {
    id: "policy-012",
    patientId: "patient-009",
    policyType: "PRIMARY",
    payerName: "Aetna",
    payerId: "60054",
    memberId: "AET-556677889",
    groupNumber: "GRP-FIN500",
    subscriberName: "Lisa Taylor",
    subscriberRelationship: "Self",
    planName: "Aetna Choice POS II",
    planType: "POS",
    effectiveDate: new Date("2024-01-01"),
    rxBin: "004336",
    rxPcn: "MEDDADV",
    copayPcp: 25,
    copaySpecialist: 45,
  },
  // Patient 010 - Primary (HDHP with HSA)
  {
    id: "policy-013",
    patientId: "patient-010",
    policyType: "PRIMARY",
    payerName: "UnitedHealthcare",
    payerId: "87726",
    memberId: "UHC-223344556",
    groupNumber: "GRP-STARTUP",
    subscriberName: "Christopher Lee",
    subscriberRelationship: "Self",
    planName: "UHC HDHP Bronze",
    planType: "HDHP",
    effectiveDate: new Date("2024-01-01"),
    rxBin: "610014",
    rxPcn: "OHCARD",
  },
];

export async function seedPatients(prisma) {
  for (const patient of PATIENTS) {
    await prisma.patient.upsert({
      where: { id: patient.id },
      update: patient,
      create: patient,
    });
  }

  console.log("✅ Created sample patients");

  for (const policy of INSURANCE_POLICIES) {
    await prisma.insurancePolicy.upsert({
      where: { id: policy.id },
      update: policy,
      create: policy,
    });
  }

  console.log("✅ Created sample insurance policies");
}
